Algoritmo "MeuNome"
// Disciplina   : Lógica de Programação
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Alisson Bandeira
// Data atual  : 07/05/2023
Var
// Seção de Declarações das variáveis 
   Nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval ("Digite seu nome: ")
   Leia (Nome)
   Escreval ("Muito prazer, ", nome)

Fimalgoritmo